server:
  port: 8090

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://172.17.0.1:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config4.json
    openai:
      base-url: https://api.openai-proxy.org
      api-key: sk-k8yjC02DdOCJGxa5GEu6nJT45QxKTkor5KA1dSm4FkMMebbi
      embedding-model: text-embedding-ada-002
      chat:
        options:
          model: gpt-5.2
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://da04e4a739ea4f1f9a93-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml